"use client";

import Link from "next/link";
import { useCallback, useState } from "react";

import {
  deleteCompanyRegProfile,
  getCompanyRegProfile,
  putCompanyRegProfile,
  type CompanyRegProfile,
} from "@/lib/api";
import {
  CANONICAL_FUNCTIONS,
  CANONICAL_PRODUCTS,
  formatRegTagLabel,
  INSTITUTION_TYPES,
} from "@/lib/regulatoryProfileOptions";

function toggleInList(list: string[], value: string): string[] {
  if (list.includes(value)) return list.filter((x) => x !== value);
  return [...list, value].sort();
}

function CheckboxGroup({
  title,
  options,
  selected,
  onToggle,
}: {
  title: string;
  options: readonly string[];
  selected: string[];
  onToggle: (value: string) => void;
}) {
  return (
    <div>
      <p className="text-xs font-medium text-zinc-600 dark:text-zinc-400">{title}</p>
      <div className="mt-2 grid max-h-44 grid-cols-1 gap-1.5 overflow-y-auto rounded-lg border border-zinc-200/90 p-2 dark:border-zinc-800 sm:grid-cols-2">
        {options.map((opt) => (
          <label
            key={opt}
            className="flex cursor-pointer items-start gap-2 text-xs text-zinc-700 dark:text-zinc-300"
          >
            <input
              type="checkbox"
              checked={selected.includes(opt)}
              onChange={() => onToggle(opt)}
              className="mt-0.5 rounded border-zinc-300 text-teal-600 focus:ring-teal-500/30 dark:border-zinc-600 dark:bg-zinc-900"
            />
            <span>{formatRegTagLabel(opt)}</span>
          </label>
        ))}
      </div>
    </div>
  );
}

export function CompanyProfileAdmin({ onSaved }: { onSaved?: () => void }) {
  const [ticker, setTicker] = useState("");
  const [name, setName] = useState("");
  const [institutionTypes, setInstitutionTypes] = useState<string[]>([]);
  const [primaryProducts, setPrimaryProducts] = useState<string[]>([]);
  const [primaryFunctions, setPrimaryFunctions] = useState<string[]>([]);
  const [gicsSector, setGicsSector] = useState("");
  const [gicsSub, setGicsSub] = useState("");
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);

  const [loaded, setLoaded] = useState<CompanyRegProfile | null | "absent">(null);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [message, setMessage] = useState<{ type: "ok" | "err"; text: string } | null>(null);

  const applyProfile = useCallback((p: CompanyRegProfile | null) => {
    if (!p) {
      setLoaded("absent");
      setName("");
      setInstitutionTypes([]);
      setPrimaryProducts([]);
      setPrimaryFunctions([]);
      setGicsSector("");
      setGicsSub("");
      setIsAutoGenerated(false);
      return;
    }
    setLoaded(p);
    setName(p.name);
    setInstitutionTypes([...p.institution_types]);
    setPrimaryProducts([...p.primary_products]);
    setPrimaryFunctions([...p.primary_functions]);
    setGicsSector(p.gics_sector ?? "");
    setGicsSub(p.gics_sub_industry ?? "");
    setIsAutoGenerated(p.is_auto_generated);
  }, []);

  const loadProfile = useCallback(async () => {
    const t = ticker.trim().toUpperCase();
    if (!t) {
      setMessage({ type: "err", text: "Enter a ticker first." });
      return;
    }
    setMessage(null);
    setLoading(true);
    try {
      const p = await getCompanyRegProfile(t);
      applyProfile(p);
      setMessage(
        p
          ? { type: "ok", text: `Loaded profile for ${t}.` }
          : { type: "ok", text: `No profile for ${t} — fill the form and save to create one.` },
      );
    } catch (e) {
      setMessage({ type: "err", text: e instanceof Error ? e.message : "Load failed" });
    } finally {
      setLoading(false);
    }
  }, [ticker, applyProfile]);

  const saveProfile = useCallback(async () => {
    const t = ticker.trim().toUpperCase();
    if (!t) {
      setMessage({ type: "err", text: "Enter a ticker." });
      return;
    }
    if (!name.trim()) {
      setMessage({ type: "err", text: "Company name is required." });
      return;
    }
    setMessage(null);
    setSaving(true);
    try {
      const saved = await putCompanyRegProfile(t, {
        name: name.trim(),
        institution_types: institutionTypes,
        primary_products: primaryProducts,
        primary_functions: primaryFunctions,
        gics_sector: gicsSector.trim() || null,
        gics_sub_industry: gicsSub.trim() || null,
        is_auto_generated: isAutoGenerated,
      });
      applyProfile(saved);
      setMessage({ type: "ok", text: `Saved profile for ${saved.ticker}.` });
      onSaved?.();
    } catch (e) {
      setMessage({ type: "err", text: e instanceof Error ? e.message : "Save failed" });
    } finally {
      setSaving(false);
    }
  }, [
    ticker,
    name,
    institutionTypes,
    primaryProducts,
    primaryFunctions,
    gicsSector,
    gicsSub,
    isAutoGenerated,
    applyProfile,
    onSaved,
  ]);

  const deleteProfile = useCallback(async () => {
    const t = ticker.trim().toUpperCase();
    if (!t) {
      setMessage({ type: "err", text: "Enter a ticker." });
      return;
    }
    if (typeof loaded !== "object" || loaded === null || loaded.ticker !== t) {
      setMessage({ type: "err", text: "Load the profile for this ticker first so it matches the ticker field." });
      return;
    }
    if (
      !window.confirm(
        `Delete regulatory profile for ${t}? Ticker impact matching will return 404 until you save a new profile.`,
      )
    ) {
      return;
    }
    setMessage(null);
    setDeleting(true);
    try {
      await deleteCompanyRegProfile(t);
      applyProfile(null);
      setMessage({ type: "ok", text: `Deleted profile for ${t}.` });
      onSaved?.();
    } catch (e) {
      setMessage({ type: "err", text: e instanceof Error ? e.message : "Delete failed" });
    } finally {
      setDeleting(false);
    }
  }, [ticker, loaded, applyProfile, onSaved]);

  const tUpper = ticker.trim().toUpperCase();
  const canDelete =
    typeof loaded === "object" && loaded !== null && loaded.ticker === ticker.trim().toUpperCase() && ticker.trim().length > 0;

  return (
    <section className="surface-card mt-8 p-5 sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">Company profile</h2>
          <p className="mt-1 max-w-xl text-sm text-zinc-600 dark:text-zinc-400">
            Map each ticker to products and functions so{" "}
            <Link href="/" className="font-medium text-teal-600 hover:underline dark:text-teal-400">
              home
            </Link>{" "}
            and{" "}
            <Link href="/company/JPM" className="font-medium text-teal-600 hover:underline dark:text-teal-400">
              company dashboards
            </Link>{" "}
            can match Federal Register rules. Values must match the enrichment model enums.
          </p>
        </div>
        {tUpper ? (
          <Link
            href={`/company/${encodeURIComponent(tUpper)}`}
            className="text-sm font-medium text-teal-600 hover:underline dark:text-teal-400"
          >
            Open {tUpper} dashboard →
          </Link>
        ) : null}
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-12">
        <div className="flex flex-wrap gap-2 lg:col-span-12">
          <div className="min-w-[8rem] flex-1">
            <label className="text-xs font-medium text-zinc-600 dark:text-zinc-400">Ticker</label>
            <input
              value={ticker}
              onChange={(e) => setTicker(e.target.value.toUpperCase())}
              placeholder="JPM"
              maxLength={16}
              className="mt-1 w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 font-mono text-sm outline-none focus:border-teal-500/50 focus:ring-2 focus:ring-teal-500/30 dark:border-zinc-700 dark:bg-zinc-900/80"
            />
          </div>
          <div className="min-w-[12rem] flex-[2]">
            <label className="text-xs font-medium text-zinc-600 dark:text-zinc-400">Company name</label>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Display name"
              className="mt-1 w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm outline-none focus:border-teal-500/50 focus:ring-2 focus:ring-teal-500/30 dark:border-zinc-700 dark:bg-zinc-900/80"
            />
          </div>
          <div className="flex flex-wrap items-end gap-2">
            <button
              type="button"
              onClick={loadProfile}
              disabled={loading || saving || deleting}
              className="btn-secondary text-sm"
            >
              {loading ? "Loading…" : "Load"}
            </button>
            <button
              type="button"
              onClick={saveProfile}
              disabled={loading || saving || deleting}
              className="btn-primary text-sm"
            >
              {saving ? "Saving…" : "Save"}
            </button>
            <button
              type="button"
              onClick={deleteProfile}
              disabled={loading || saving || deleting || !canDelete}
              className="rounded-xl border border-red-200/90 bg-white px-3 py-2 text-sm font-medium text-red-700 transition hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-40 dark:border-red-900/50 dark:bg-zinc-950 dark:text-red-300 dark:hover:bg-red-950/30"
            >
              {deleting ? "Deleting…" : "Delete"}
            </button>
          </div>
        </div>

        <div className="lg:col-span-6">
          <label className="text-xs font-medium text-zinc-600 dark:text-zinc-400">GICS sector (optional)</label>
          <input
            value={gicsSector}
            onChange={(e) => setGicsSector(e.target.value)}
            className="mt-1 w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm outline-none focus:border-teal-500/50 focus:ring-2 focus:ring-teal-500/30 dark:border-zinc-700 dark:bg-zinc-900/80"
          />
          <label className="mt-3 block text-xs font-medium text-zinc-600 dark:text-zinc-400">
            GICS sub-industry (optional)
          </label>
          <input
            value={gicsSub}
            onChange={(e) => setGicsSub(e.target.value)}
            className="mt-1 w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm outline-none focus:border-teal-500/50 focus:ring-2 focus:ring-teal-500/30 dark:border-zinc-700 dark:bg-zinc-900/80"
          />
          <label className="mt-3 flex cursor-pointer items-center gap-2 text-xs text-zinc-600 dark:text-zinc-400">
            <input
              type="checkbox"
              checked={isAutoGenerated}
              onChange={(e) => setIsAutoGenerated(e.target.checked)}
              className="rounded border-zinc-300 text-teal-600 dark:border-zinc-600"
            />
            Mark as auto-generated
          </label>
        </div>

        <div className="space-y-4 lg:col-span-6">
          <CheckboxGroup
            title="Institution types"
            options={INSTITUTION_TYPES}
            selected={institutionTypes}
            onToggle={(v) => setInstitutionTypes((prev) => toggleInList(prev, v))}
          />
        </div>

        <div className="lg:col-span-6">
          <CheckboxGroup
            title="Primary products"
            options={CANONICAL_PRODUCTS}
            selected={primaryProducts}
            onToggle={(v) => setPrimaryProducts((prev) => toggleInList(prev, v))}
          />
        </div>

        <div className="lg:col-span-6">
          <CheckboxGroup
            title="Primary functions"
            options={CANONICAL_FUNCTIONS}
            selected={primaryFunctions}
            onToggle={(v) => setPrimaryFunctions((prev) => toggleInList(prev, v))}
          />
        </div>
      </div>

      {loaded !== null ? (
        <p className="mt-4 text-xs text-zinc-500">
          {loaded === "absent" ? "No row in the database yet for this ticker — save to create." : "Editing existing profile."}
        </p>
      ) : null}

      {message ? (
        <div
          className={
            message.type === "ok"
              ? "mt-4 rounded-lg border border-emerald-200/90 bg-emerald-50/90 px-3 py-2 text-sm text-emerald-900 dark:border-emerald-900/40 dark:bg-emerald-950/40 dark:text-emerald-100"
              : "mt-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200"
          }
        >
          {message.text}
        </div>
      ) : null}
    </section>
  );
}
